// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbVy8td73NHZmlUCnpWrUSvgMkyTczEhQ',
    appId: '1:654759295950:web:68e01eeb94aafe4834499f',
    messagingSenderId: '654759295950',
    projectId: 'travelling-app-7aee1',
    authDomain: 'travelling-app-7aee1.firebaseapp.com',
    databaseURL: 'https://travelling-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'travelling-app-7aee1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1qHQdQVn3OcbNyRIEqSjq3TOogOEnVDU',
    appId: '1:654759295950:android:9abb75fe4f47c9fc34499f',
    messagingSenderId: '654759295950',
    projectId: 'travelling-app-7aee1',
    databaseURL: 'https://travelling-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'travelling-app-7aee1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKARBeD46M5g_-syU_u9uHYaLE3VmJsuQ',
    appId: '1:654759295950:ios:fc3ce899ef9974cd34499f',
    messagingSenderId: '654759295950',
    projectId: 'travelling-app-7aee1',
    databaseURL: 'https://travelling-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'travelling-app-7aee1.appspot.com',
    iosBundleId: 'com.example.travellingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKARBeD46M5g_-syU_u9uHYaLE3VmJsuQ',
    appId: '1:654759295950:ios:297891406af9a68a34499f',
    messagingSenderId: '654759295950',
    projectId: 'travelling-app-7aee1',
    databaseURL: 'https://travelling-app-7aee1-default-rtdb.firebaseio.com',
    storageBucket: 'travelling-app-7aee1.appspot.com',
    iosBundleId: 'com.example.travellingApp.RunnerTests',
  );
}
